### ISSUE TITLE
Spam Chat healingTaken /HealingOut

### ISSUE THREAD

**Issue by Apukus** [dandruff/xCT#219] opened 2022-11-17 01:49 UTC
First i love your add as Affli!!
Since the last update the xct+ addon spams my primary chat with the following messages.

FRAME: healing xct+ say there is no color named: healingTaken
FRAME: outgoing xct+ say there is no color named: healingOut

The second problem is xct can no longer be opened with /xct to configure it 
![image](https://user-images.githubusercontent.com/118409552/202334155-9371fd68-57c7-4f0b-a738-8f2e7b891f01.png)

**Comment by bv101rj** [comment] 2022-11-17 02:05
You can close this if you want, its a dupe of this issue https://github.com/dandruff/xCT/issues/217

**Closed** 2024-12-18 17:42 UTC
